name: Build & Publish

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'repo'
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Dependencies
        working-directory: repo
        run: npm install
      - name: Build Site
        working-directory: repo
        run: npm run build
      - name: Build DB
        working-directory: repo
        run: npm run build:db -- "$GITHUB_SHA"
      - name: Checkout GH Pages
        uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
          token: '${{ secrets.SERVICE_PAT }}'
          path: 'gh-pages'
      - name: Remove Existing Docs Directory
        working-directory: gh-pages
        run: rm -rf docs
      - name: Create Docs Directory
        working-directory: gh-pages
        run: mkdir -p docs
      - name: Create CNAME File
        working-directory: gh-pages
        run: echo 'www.canitmux.com' > docs/CNAME
      - name: Copy Distribution Folder to Docs
        run: cp -R repo/dist/* gh-pages/docs/
      - name: Create Version Text File
        working-directory: gh-pages
        run: echo "$GITHUB_SHA" > docs/version.txt
      - name: Stage Pages
        working-directory: gh-pages/docs
        run: git add -A
      - name: Commit Pages
        working-directory: gh-pages
        run: |
          git config --global user.email "canitmuxservice@gmail.com"
          git config --global user.name "canitmux Service Account"
          git commit -m "Pages for $GITHUB_SHA"
      - name: Push Pages
        working-directory: gh-pages
        run: git push origin gh-pages